### ISSUE TITLE
Lunr throws in Safari sometimes when calling the query method

### ISSUE THREAD

**Issue by imaustink** [olivernn/lunr.js#279]
When calling the `.query` method with certain search terms in Safari, the following error is thrown:
```
TypeError: undefined is not an object (evaluating 'posting._index') 
```
The problem is [here](https://github.com/olivernn/lunr.js/blob/master/lunr.js#L1809). Adding an check for `posting` solves the problem but I am almost certain this is a sign of a larger problem and this should be fixed upstream.

**Comment by chasenlehara** [comment]
@olivernn, I work with @imaustink and we’d like to contribute to get this bug fixed, but I’m not sure where to start in determining why either the `invertedIndex` wouldn’t have the `expandedTerm` for the query, or why a bad `expandedTerm` would be generated.

Our project is open source and we are happy to provide any info that’s useful, or if you can point us in the right direction we will happily work on it. Thanks for the great project and for your help. 🙏

**Comment by chasenlehara** [comment]
We’re using a fork with [this commit](https://github.com/bit-docs/lunr.js/commit/edcdc14c82723305ddaba88e88281c7ae7914de4) (reference above) until we can figure out the root issue.

**Comment by olivernn** [comment]
@imaustink @chasenlehara thanks for taking the time to help with this issue, its a real help!

I think the first step is to get a reduced test case. Without that its going to be really tricky to track this down. Even a non-reduced test case would be a start.

From the looks of it, it seems the bug is being triggered by some specific combination of query and document content. Why this would only happen in Safari I don't know, there isn't anything particularly special happening.

**Comment by chasenlehara** [comment]
What does the ideal reduced test case look like? A sample project that has data, sets up indexing and querying, and reproduces the exception? Or should we look into modifying any of the [current tests](https://github.com/olivernn/lunr.js/tree/master/test)?

**Comment by olivernn** [comment]
In the past people have put together reproductions with jsfiddle. The ideal would be having an index with a single document and a query that triggers the bug.

An example fiddle for some inspiration - https://jsfiddle.net/of54k0uk/14/

**Comment by altmail** [comment]
Hello, if it can help, it's not only with safari, I reproduce the error in react native / android too.

`
searchMerchant(keywords)
{

    //let found = this.idx.search(keywords)
    if (keywords == '') return {}
    let listkeywords = keywords.split(' ')
    let found = this.idx.query(function (q) {
        q.term(keywords, { usePipeline: true, boost: 30 })


        listkeywords.forEach(function (keyword) {
            q.term(keyword, {
                fields: ['title',
                         'title_broken_space_bar',
                         'keywords',
                         'keywords_why_no_space_bar',
                         'categories',
                         'categoriesnoaccents'],
                wildcard: lunr.Query.wildcard.TRAILING
            });
        });

    });
}
`
I generate or load the index if not in cache, the error seem to trig only when the index is generated, when loaded from cache with lunr.Index.load() the error seems to never trig. 

![screenshot_1499937955](https://user-images.githubusercontent.com/8913366/28160343-3783b902-67c0-11e7-9122-3f2f7ecf7c8f.png)

**Comment by olivernn** [comment]
@Julinar interesting, so you're workaround was to prevent empty searches? Was this what was causing the issue.

As I mentioned earlier in the issue, without more details to go on, specifically a simple reproduction, its very difficult for me to try and provide a fix. If you can put together a simple test case that shows the issue I can get to fixing it straight away.

**Comment by imaustink** [comment]
@chasenlehara and I were able to create a reduced test case. Open this [jsfiddle](https://jsfiddle.net/0bseofjq/11/) in Safari and you will see the error. I hope this helps.

**Comment by olivernn** [comment]
@imaustink thanks, that is super useful!

I've only had a very quick look, but certainly something strange is happening! You are searching for `"can*"`, and when I pause the debugger on the thrown exception I see that Lunr has somehow expanded that into "can-centa", which is weird because that _definitely_ isn't in the index.

So somehow `this.tokenSet.intersect(termTokenSet).toArray()` is inventing new terms, and only in Safari.

I'll do some more digging and let you know what I find.

**Comment by olivernn** [comment]
Hmm, where did that unicode come from? I pasted that directly from the debugger, so _maybe_ that is the cause of the weirdness....

**Comment by olivernn** [comment]
So I've been trying to understand what is going on in Safari using the debugger, if I pause on exceptions I can see that the expanded terms that are being looked for are `["can-compon", "can-centa"]`, however if I step through the `lunr.TokenSet#intersect` method the result is what I would consider the correct expanded terms: `["can-compon", "can-componenta"]`.

This might be tricky...

**Comment by olivernn** [comment]
I've tried to reduce the test case some more (no doubt it can be reduced further later) and I'm very confused - https://jsfiddle.net/23fujmvf/1/

By alerting the results of the `lunr.TokenSet#intersect` the problem goes away, i.e. it seems to change the string that is being returned.

Without the alert we get something that looks like "can-centa" which looks like it has dropped the "ompon" part of "can-componenta".

Perhaps `alert` is somehow normalising the string (remember those weird unicode symbols from above), but I find this _very_ unexpected.

**Comment by imaustink** [comment]
@olivernn, thanks for jumping on this so quickly!

I did some experimentation as well before making the test case, and I also noticed the unicode characters, and the fact that observing the string seems to fix the problem. Merely [testing the string with RegEx](https://jsfiddle.net/egLzL24L/1/) is one example of this, [comparing the string](https://jsfiddle.net/egLzL24L/4/) is another example. In addition, I just discovered that even [inspecting a copy of the string](https://jsfiddle.net/egLzL24L/5/) seems to fix the problem.

This behavior is very unexpected indeed. This definitely seems like a bug in Safari rather than Lunr. Although I am curious how Lunr seems to be the only library having issues with this currently. Perhaps there is a very obscure bug that Lunr is somehow invoking? Please let me know if there is anything I can do to help with this issue. 🍻

**Comment by olivernn** [comment]
@imaustink no problem, its certainly an interesting case!

I'm pretty sure this is a bug in Safari, not that that helps us much, Lunr will need to work around it _somehow_ and I don't think using `alert` is going to cut it!

To be able to get any traction with a browser bug we're going to have to have a much reduced test case, ideally one that does not involve any Lunr code at all. My current theory is that it is an issue with how Lunr is [getting characters from strings](https://github.com/olivernn/lunr.js/blob/master/lib/token_set_builder.js#L8-L46), and how it is then [putting those characters back together again to form a string](https://github.com/olivernn/lunr.js/blob/master/lib/token_set.js#L282-L316), perhaps it isn't correctly handling multi byte characters? That is just a guess though.

I think the interesting thing is how something like `alert` 'fixes' the issue. My understanding would be that `alert` does not modify its parameters, indeed, strings in JavaScript are immutable, so _how_ does it fix the issue? Is it normalising unicode or something. Maybe this would give us a clue as to what is going on?

I'm going to carry on poking around with the debugger, but please let me know if you come up with something too.

**Comment by olivernn** [comment]
One thing you could try is to use something similar to [lunr-unicode-normalizer](https://github.com/cvan/lunr-unicode-normalizer/blob/master/lunr.unicodeNormalizer.js). That repo is not updated for Lunr 2, but the idea is the same, remove all diacritic marks. Not a fix, but might be a reasonable work around for now.

**Comment by olivernn** [comment]
Okay, this is definitely an issue with unicode, I'm not sure where the issue is, but using [`String#normalize`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/normalize) seems to fix the problem - https://jsfiddle.net/23fujmvf/2/

I don't think `String#normalize` has good enough browser support yet to just use that in Lunr, though I could be wrong. Also, its still weird that this is required in Safari, but not Chrome or Firefox.

**Comment by imaustink** [comment]
Very Interesting. `String.prototype.normalize` is supported in Safari 10 and up. What do you think about identifying Safari and normalizing if available? I don't see a reason to normalize in other browsers so support really shouldn't be a concern in my opinion. That is as long as supporting Safari 10+ is acceptable.

**Comment by olivernn** [comment]
Ok, I think the problem is being caused by [`lunr.trimmer`](https://github.com/olivernn/lunr.js/blob/master/lib/trimmer.js). It tries to remove any trailing punctuation from terms before they enter the index, but it does so with a fairly naive regular expression. To be fair, it does say that its not great at non-latin characters, but its certainly not something that would be immediately obvious. By removing the trimmer the [test case](https://jsfiddle.net/23fujmvf/3/) behaves as expected.

This is _probably_ the cause in this case, since one of the terms has some trailing, non-latin, characters. My guess is that it is mangling the final 'character' which by removing half of the code point that makes up the full character. Without any other test cases its difficult to say if this is _always_ the cause.

So, as an immediate fix, the trimmer can be removed from the builder pipeline:

```javascript
lunr(function () {
  this.pipeline.remove(lunr.trimmer)
})
```

The existing implementation could possibly be made more robust against these cases, I'll have to think about the best way to implement that.

In addition, Safari is certainly doing _something_ unexpected (as far as I'm concerned). It's now probably easier to produce a test case that doesn't directly involve Lunr, I'll update here when I've done that.

**Comment by olivernn** [comment]
I've been doing some thinking about this and I think an approach forward is to improve the quality of the implementation of `lunr.tokenizer`. Its job is to turn some text into individual words or tokens. The fact that `lunr.trimmer` even exists suggests some inadequacy in the implementation of `lunr.tokenzier`. More generally, unicode is hard, and texts with non latin characters are not really well supported by the current approach.

I think an approach based on [UAX#29](http://unicode.org/reports/tr29/#ALetter) is probably more robust, though the implementation details are certainly more involved. I'm going to experiment with writing a tokeniser using the rules in the above document, I want to see how much better it is able to deal with these cases, as well as understanding what, if any, impact there is on performance (both speed and library size).

In the meantime I'm still interested in seeing if this bug can be isolated enough to show to the Safari developers, as its current behaviour is still _weird_ to me.

**Comment by escofield** [comment]
i was faced with the same issue and removing the trimmer from the pipeline solved my error as well.

**Comment by fbennett** [comment]
We found that cloning the clause for each term in ``index.js`` cleared this error for us. I'm not sure if that is related to, or less or more drastic than, removing trimmer, but I'll tie it into this thread for completeness. The issue that we experienced and the patch are at #327.

**Comment by nbuonin** [comment]
I'm seeing the same bug on this I'm working on [site](https://polar-hub.github.io/polarhub//database/).  I've tried both work arounds mentioned above: removing the trimmer and cloning the clause for each term - neither worked though.

One kludgey thing that did work was to console.log out each expandedTerm here: https://github.com/olivernn/lunr.js/blob/fd5dccdbb81fc47e0d1f431a392f8c934d4eb39d/lib/index.js#L181
In my case this was 3000+ terms.  And it only works when I log every term.  If I set a conditional to log only the index and term that throws the bug, then it breaks.  If I log an arbitrary string it still breaks.

Lastly, the index of expanded terms that causes the bug seems to change.  In my brief testing it was words that began with 'w' and the strings did not contain non-latin chars.

Talking through this with a coworker, he thought this suggested some kind of race condition - perhaps the logging and evaluating the array index slowed things down just enough to sort itself out.

**Comment by dawez** [comment]
Is there any update on this issue? I also noticed that I have broken search on safari.

**Comment by lucaong** [comment]
Just to add more to this, there is something curious with the "misterious" fixes to this issue.
It does not really matter what one does with the expanded term: just calling any method defined on `String.prototype` (even without actually using the result) fixes this bug:

https://jsfiddle.net/egLzL24L/40/  (see the `.charAt(0)` on line 17. Removing it causes the bug to re-appear)

Interestingly, calling methods higher in the prototype chain (like on `Object.prototype`), does not work. It seems like Safari "casts" the string to its correct representation only when a string method is first called on it.

It would be interesting to understand the underlying cause of this, but the observation offers a possible viable solution for the moment: just call an inexpensive string method on the expanded term before retrieving it from the inverted index.

**Comment by lucaong** [comment]
I think I managed to pinpoint the exact place in `lunr.TokenSet` where the string gets sometimes corrupted in Safari:

https://jsfiddle.net/egLzL24L/77/ (see line 38 and relevant comment)

It seems that the string concatenation (no matter if done with `.concat` or with `+`) results in the corruption, which is fixed by calling any `String.prototype` method on the string. The two strings that get concatenated look fine, only the result is corrupted.

As of why this happens, and what exactly triggers it, I have no clue. I would be inclined to think that some underlying memory optimization of string concatenation is buggy in Safari in some corner case.

**Comment by lucaong** [comment]
and here is the smallest script where I can reproduce the bug.

https://jsfiddle.net/egLzL24L/156/

It seems like it's a combination of the trimmer RegExp, a trailing non-word, a Unicode character in a higher block than Latin-1 Supplement, and string concatenation.

**Comment by lucaong** [comment]
And here the bug is reproduced without Lunr, just a short snippet of code similar to the way Lunr builds a TokenSet and then turns it into an array.

https://jsfiddle.net/8zn2fj6s/18/

Note that if you copy/paste the output of the alert when the bug occurs, and inspect it's binary content with `xxd` there are null bytes (`00`) that corrupt the string. Can anybody get it even smaller than this? I think we could file a bug with Safari.

**Comment by lucaong** [comment]
Ok, this seems the minimum script that reproduces it. No Lunr code nor any complex data structure is involved:
 
https://jsfiddle.net/DukeLeNoir/mkrfw4g8/

**Comment by lucaong** [comment]
I took the liberty to file a bug report on Safari, as this is now clearly a browser bug and not a Lunr issue.

**Comment by olivernn** [comment]
@lucaong nice work! Are you able to share the link to the Safari bug report?

I *think* that this is really a bug in the way that Lunr handles (or doesn't) unicode. In both `lunr.TokenSet` and `lunr.tokenizer` lunr attempts to get a 'character' from a string, either with `String#charAt` or `String#[]`.

My understanding (mostly from reading [this article](https://mathiasbynens.be/notes/javascript-unicode)) is that neither of those methods handle unicode characters particularly well.

Safari is certainly doing something _different_ to other browsers here, maybe its a bug. The workaround certainly suggests something odd is happening.

I think your workaround is probably the right approach for now, I'll take a look and get a release out in the next day or so. A more long term fix is to make both `lunr.tokenizer` and `lunr.TokenSet` less naive when it comes to getting characters from strings.

**Comment by lucaong** [comment]
@olivernn I filed the bug at https://bugreport.apple.com, it has number 42468541 but does not seem to be publicly visible. No response so far, but I will keep you updated.

You're right, unicode handling is mostly lacking in JS, but that should not lead to a corrupted string. Besides, the null characters could be the native string terminator leaking out, so there's the risk that someone more skilled than me could devise a way to leverage this bug to expose more memory content.

Regarding the fix, on the good side it should not affect performance nor change the Lunr behavior in any way. It is quite surprising though, so it might be worth writing a test for the `toArray` method to avoid regressions when this part of code is changed.

- By the way, thanks for Lunr, it's really an amazing library!

**Comment by chasenlehara** [comment]
@lucaong It might be worth [reporting a WebKit bug](https://webkit.org/reporting-bugs/) so we have some visibility into their process.

Thank you so much for taking the time to debug this issue more!

**Comment by olivernn** [comment]
The patch from @lucaong is now on master, so if anyone wants to try out the bleeding edge they can. A proper release will follow shortly.

**Comment by lucaong** [comment]
@chasenlehara thanks for the link, I filed this bug there: https://bugs.webkit.org/show_bug.cgi?id=187947

**Comment by olivernn** [comment]
I've just pushed 2.3.1 to npm which includes the patch from @lucaong.

I'm going to leave this issue open for now until I get around to updating the tokeniser and token store to be more aware of unicode.

**Comment by hftf** [comment]
With lunr 2.3.6 and the trimmer removed from the pipeline, I still encounter this issue sporadically.

The patch in #361 may have been insufficient or too localized. Maybe it should be guaranteed that an undefined `posting` doesn't get past that line?

I see that the issue was already thoroughly investigated more than I can meaningfully contribute to. Anecdotally, it often happens when the term is empty (or stopwords), but I saw it happen with `*m*` several times too. I also use lunr-unicode-normalizer (monkey-patched for 2.x) for the rare document with Unicode text.

**Comment by brutuscat** [comment]
Apparently the fix reported by @lucaong has been fixed https://trac.webkit.org/changeset/255975/webkit and it lives now in the Safari Tech. Preview https://webkit.org/blog/10031/release-notes-for-safari-technology-preview-101/

**Comment by khromov** [comment]
Hi, we have exactly the same problem in our application, affecting all browsers. It seems to affect some entries specifically but we cannot find anything special about these entries, and shuffling the entries around leads to other entries being broken. It is related to searching for wildcards, removing wildcards fixes it. Any ideas how we can start to debug this?

```
Uncaught TypeError: Cannot read properties of undefined (reading '_index')
    at lunr.Index.query (lunr.js:2048:1)
    at lunr.Index.search (lunr.js:1929:1)
    at Search.search (search.ts:87:32)
...
```

The line in question:

```
        var expandedTerm = expandedTerms[j],
            posting = this.invertedIndex[expandedTerm],
           (X) termIndex = posting._index
```

**Comment by bukowskiadam** [comment]
@khromov We've found the issue to be related to this one: https://github.com/olivernn/lunr.js/issues/503
Creating a "fixed" version of lunr like this fixes the problem for us


<details>
<summary><i>source code collapsed for clarity, because it's long</i></summary>

```ts
import lunr from 'lunr';

/**
 * This file is a workaround for a bug in the lunr library. The bug is described in this issue,
 * which also provides a solution that works for us:
 * https://github.com/olivernn/lunr.js/issues/503
 */

declare global {
  namespace lunr {
    interface TokenSet {
      _str: string;
      final: boolean;
      edges: Record<string, lunr.TokenSet>;
      id: number;
    }
  }
}

lunr.TokenSet.prototype.toString = function () {
  if (this._str) {
    return this._str;
  }

  var str = this.final ? '1' : '0',
    labels = Object.keys(this.edges).sort(),
    len = labels.length;

  for (var i = 0; i < len; i++) {
    var label = labels[i],
      node = this.edges[label];

    str = str + ', L(' + label + ')I(' + node.id + ')';
  }

  return str;
};

export default lunr;
```

</details>
